%{
EGR102PlaySong - Uses MATLAB to play a song
Authors:    Nathan Jones
Assignment: EGR 102-010 Play Song
Changed:    6 December 2023
History:    None
Purpose:
 Uses MATLAB to play a song using various frequencies

Notes: None
%}

%%% Arduino configuration: change these lines as necessary
clear;
a = arduino();

%%% Your program goes here. Variable a is your Arduino object.

% Frequencies of musical notes, in Hz.
C = 262;
D = 294;
E = 330;
F = 349; % This is equal to E#
G = 392;

Rest = 0;

% Durations of musical notes, in seconds.
Whole = 0.6;
Half = Whole / 2;
Quarter = Whole / 4;

% The song to play.  Column 1 is the note, column 2 the duration. 
Song = [ E,     Quarter; ...
         E,     Quarter; ...
         E,     Half; ...
         Rest,  Quarter; ...
         E,     Quarter; ...
         E,     Quarter; ...
         E,     Half; ...
         Rest,  Quarter; ...
         E,     Quarter; ...
         G,     Quarter; ...
         C,     Quarter; ...
         D,     Quarter; ...
         E,     Whole; ...
         F,     Quarter; ...
         F,     Quarter; ...
         F,     Quarter; ...
         F,     Quarter; ...
         F,     Quarter; ...
         E,     Quarter; ...
         E,     Quarter; ...
         E,     Quarter; ...
         E,     Quarter; ...
         E,     Quarter; ...
         D,     Quarter; ...
         D,     Quarter; ...
         E,     Quarter; ...
         D,     Half; ...
         G,     Half; ...
         E,     Quarter; ...
         E,     Quarter; ...
         E,     Half; ...
         E,     Quarter; ...
         E,     Quarter; ...
         E,     Half; ...
         E,     Quarter; ...
         G,     Quarter; ...
         C,     Quarter; ...
         D,     Quarter; ...
         E,     Whole; ...
         F,     Quarter; ...
         F,     Quarter; ...
         F,     Quarter; ...
         F,     Quarter; ...
         F,     Quarter; ...
         E,     Quarter; ...
         E,     Quarter; ...
         E,     Quarter; ...
         E,     Quarter; ...
         G,     Quarter; ...
         G,     Quarter; ...
         F,     Quarter; ...
         D,     Quarter; ...
         C,     Whole; ...
         



         C * 2, Half; ...    % Multiplying by two goes up an octave
       ];

while true
    if readDigitalPin(a, 'D2')
        
        for idx = 1 : length(Song) % number of rows
            playTone(a, 'D9', Song(idx, 1), Song(idx, 2));
            % Wait until the note is over before starting the next one.
            pause(Song(idx, 2));
        end
    end
end





